apiVersion: apps/v2
kind: Deployment
metadata:
  name: htmldeployment
spec:
   selector:
     matchLabels:
        app: html
   template:
     metadata:
       labels:
         app: html
     spec:
     - containers:
       name: htmlcontainer
       image: devopschand/statichtml
       ports:
       - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: htmlservice
spec:
  selector:
    app: html
  type: NodePort
  ports:
  - port: 8080
    targetPort: 80
